# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("http://127.0.0.1:5001/home") #change this to your port.
    self.driver.set_window_size(1296, 736)
    self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-chevron-right").click()
    self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-chevron-right").click()
    self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-chevron-right").click()
    self.driver.find_element(By.LINK_TEXT, "Next").click()
    self.driver.find_element(By.LINK_TEXT, "Next").click()
    element = self.driver.find_element(By.LINK_TEXT, "Next")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.LINK_TEXT, "Next").click()
    self.driver.find_element(By.LINK_TEXT, "Next").click()
    self.driver.find_element(By.LINK_TEXT, "Previous").click()
    self.driver.find_element(By.ID, "about-us-btn").click()
    self.driver.find_element(By.ID, "requests-btn").click()
    self.driver.find_element(By.ID, "signup").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("test9@example.com")
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("test9")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Test987654321")
    self.driver.find_element(By.ID, "confirm").click()
    self.driver.find_element(By.ID, "confirm").send_keys("Test987654321")
    self.driver.find_element(By.ID, "role").click()
    dropdown = self.driver.find_element(By.ID, "role")
    dropdown.find_element(By.XPATH, "//option[. = 'Patron']").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login-btn:nth-child(2)").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("test9")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Test987654321")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "requests-btn").click()
    self.driver.find_element(By.ID, "first_name").click()
    self.driver.find_element(By.ID, "first_name").send_keys("test9")
    self.driver.find_element(By.ID, "last_name").click()
    self.driver.find_element(By.ID, "last_name").send_keys("tester9")
    self.driver.find_element(By.ID, "address").click()
    self.driver.find_element(By.ID, "address").send_keys("tester way tester street")
    self.driver.find_element(By.ID, "suburb").click()
    self.driver.find_element(By.ID, "suburb").send_keys("Terth")
    self.driver.find_element(By.ID, "phone").click()
    self.driver.find_element(By.ID, "phone").send_keys("0987654321")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("test9@example.com")
    self.driver.find_element(By.ID, "meal").click()
    dropdown = self.driver.find_element(By.ID, "meal")
    dropdown.find_element(By.XPATH, "//option[. = 'Vegan']").click()
    self.driver.find_element(By.ID, "number_of_people").click()
    self.driver.find_element(By.ID, "number_of_people").send_keys("2")
    self.driver.find_element(By.ID, "instructions").click()
    self.driver.find_element(By.ID, "instructions").send_keys("I want a Mediterranean dish")
    self.driver.find_element(By.ID, "submitBtn").click()
    self.driver.find_element(By.ID, "query").click()
    self.driver.find_element(By.ID, "query").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".order-box:nth-child(3) > .instructions-box").click()
    self.driver.find_element(By.CSS_SELECTOR, ".order-box:nth-child(3) > .instructions-box > strong").click()
    self.driver.find_element(By.ID, "suburb").click()
    self.driver.find_element(By.ID, "suburb").send_keys("Terth")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".order-box > div:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".order-box > div:nth-child(4)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".order-box > div:nth-child(4)")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".order-box > div:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".order-box > div:nth-child(4)").click()
    self.driver.find_element(By.ID, "home-btn").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "logout-btn").click()
    self.driver.find_element(By.NAME, "action").click()
    self.driver.close()
  
